CREATE TABLE EMPLOYEES(
   ID INT  PRIMARY KEY    NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL);

INSERT INTO EMPLOYEES (ID,NAME,AGE)
VALUES
   (1,"Tymon",	28),
   (2,"Szymon", 32);